name: Github Pages Deploy

on:
  workflow_dispatch:
  inputs:
    validation-status:
      description: 'Validation status'
      required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Pkl language
        run: |
          curl -L -o pkl 'https://github.com/apple/pkl/releases/download/0.26.3/pkl-linux-amd64'
          chmod +x pkl
          sudo mv pkl /usr/local/bin/pkl
    
      - name: Build
        run: pkl eval -f json style.pkl > docs/style.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
